// tslint:disable:object-literal-key-quotes
export const attributes = {
  'request': {
    'Author affiliation ID': 'AA.AfId',
    'Author affiliation name': 'AA.AfN',
    'Author ID': 'AA.AuId',
    'Normalized author name': 'AA.AuN',
    'Original author name': 'AA.DAuN',
    'Original affiliation name': 'AA.DAfN',
    'Numeric position in author list': 'AA.S',
    'Unique, normalized words in abstract': 'AW',
    'BibTex document type': 'BT',
    'BibTex venue name': 'BV',
    'Conference series ID': 'C.CId',
    'Conference series name': 'C.CN',
    'Citation count': 'CC',
    'Citation contexts': 'CitCon',
    'Date': 'D',
    'Original paper title': 'DN',
    'Digital Object Identifier': 'DOI',
    'Estimated citation count': 'ECC',
    'Original field of study name': 'F.DFN',
    'Field of study ID': 'F.FId',
    'Normalized field of study name': 'F.FN',
    'FamId': 'FamId',
    'First page of paper in publication': 'FP',
    'Publication issue': 'I',
    'Inverted abstract': 'IA',
    'Paper ID': 'Id',
    'Journal ID': 'J.JId',
    'Journal name': 'J.JN',
    'Last page of paper in publication': 'LP',
    'Publisher': 'PB',
    'Publication type': 'Pt',
    'List of referenced paper IDs': 'RId',
    'Source URLs': 'S',
    'Normalized title': 'Ti',
    'Publication volume': 'V',
    'Full name of the Journal or Conference venue': 'VFN',
    'Short name of the Journal or Conference venue': 'VSN',
    'Unique, normalized words in title': 'W',
    'Year published': 'Y',
  },
  'display': {
    'Citation Count': 'CC',
    'Est. Citation Count': 'ECC',
    'Logprob': 'logprob',
  },
  'PtMap': {
    '0': 'Unknown',
    '1': 'Journal article',
    '2': 'Patent',
    '3': 'Conference paper',
    '4': 'Book chapter',
    '5': 'Book',
    '6': 'Book reference entry',
    '7': 'Dataset',
    '8': 'Repository',
  },
  'BTMap': {
    'a': 'Journal article',
    'b': 'Book',
    'c': 'Book chapter',
    'p': 'Conference paper',
  },
}
