// tslint:disable:object-literal-key-quotes
export const attributes = {
  'request': {
    'Author affiliation ID': 'AA.AfId',
    'Author affiliation name': 'AA.AfN',
    'Author ID': 'AA.AuId',
    'Normalized author name': 'AA.AuN',
    'Original author name': 'AA.DAuN',
    'Original affiliation name': 'AA.DAfN',
    'Numeric position in author list': 'AA.S',
    'Unique, normalized words in abstract': 'AW',
    'BibTex document type': 'BT',
    'BibTex venue name': 'BV',
    'Conference series ID': 'C.CId',
    'Conference series name': 'C.CN',
    'Citation count': 'CC',
    'Citation contexts': 'CitCon',
    'Date': 'D',
    'Original paper title': 'DN',
    'Digital Object Identifier': 'DOI',
    'Estimated citation count': 'ECC',
    'Original field of study name': 'F.DFN',
    'Field of study ID': 'F.FId',
    'Normalized field of study name': 'F.FN',
    'FamId': 'FamId',
    'First page of paper in publication': 'FP',
    'Publication issue': 'I',
    'Inverted abstract': 'IA',
    'Paper ID': 'Id',
    'Journal ID': 'J.JId',
    'Journal name': 'J.JN',
    'Last page of paper in publication': 'LP',
    'Publisher': 'PB',
    'Publication type': 'Pt',
    'List of referenced paper IDs': 'RId',
    'Source URLs': 'S',
    'Normalized title': 'Ti',
    'Publication volume': 'V',
    'Full name of the Journal or Conference venue': 'VFN',
    'Short name of the Journal or Conference venue': 'VSN',
    'Unique, normalized words in title': 'W',
    'Year published': 'Y',
  },
  'display': {
    'Last Updated': 'lastUpdated',
    'Logprob': 'logprob',
    'ID': 'entity.Id',
    'Citation Count': 'entity.CC',
    'Est. Citation Count': 'entity.ECC',
    'Field': 'entity.F',
  },
  'PtMap': {
    '0': 'Unknown',
    '1': 'Journal article',
    '2': 'Patent',
    '3': 'Conference paper',
    '4': 'Book chapter',
    '5': 'Book',
    '6': 'Book reference entry',
    '7': 'Dataset',
    '8': 'Repository',
  },
  'BTMap': {
    'a': 'Journal article',
    'b': 'Book',
    'c': 'Book chapter',
    'p': 'Conference paper',
  },
  // https://api.labs.cognitive.microsoft.com/academic/v1.0/evaluate?expr=AND(Ty='6',FL=0)&model=latest&count=1000&offset=0&attributes=Id,DFN,FL
  'FieldsOfStudy': {
    71924100: 'Medicine',
    192562407: 'Materials science',
    41008148: 'Computer science',
    185592680: 'Chemistry',
    86803240: 'Biology',
    127413603: 'Engineering',
    33923547: 'Mathematics',
    121332964: 'Physics',
    15744967: 'Psychology',
    127313418: 'Geology',
    39432304: 'Environmental science',
    17744445: 'Political science',
    144133560: 'Business',
    144024400: 'Sociology',
    162324750: 'Economics',
    205649164: 'Geography',
    142362112: 'Art',
    95457728: 'History',
    138885662: 'Philosophy',
  },
}
